### ISSUE TITLE
Set up repository on Github

### ISSUE THREAD

**Issue by computer-lov** [computer-lov/Nighttime-Parenting-Device#1]
- [x] Create repository

- [x] Add collaborators

- [x] Set up Milestones

- [x] Set up Labels

- [x] Associate with Project

**Comment by BeatrizPer** [comment]
- [ ] sdas

**Comment by BeatrizPer** [comment]
The bug will be used when something isn't working correctly and a fix needs to be found.
The design label will be related to prototyping and schematics. It will be added to 
 
documentation
Improvements or additions to documentation
 
easy
Less than 30 minutes
 
hard
More than an hour
 
hardware
Related to hardware
 
medium
Between 30 minutes and an hour
 
question
Further information is requested
 
software
Related to software and coding
 
testing
This will be used when preliminary or further testing is needing to be done on a task
 
wontfix
This will not be worked on

**Comment by computer-lov** [comment]
@ffund Please review our project!
