### ISSUE TITLE
Write BOM appendix of report

### ISSUE THREAD

**Issue by arongoldberg** [computer-lov/Nighttime-Parenting-Device#16]

**Comment by BeatrizPer** [comment]
Going to start writing BOM since I can't write the UX design yet before it gets reviewed

**Comment by BeatrizPer** [comment]
![image](https://user-images.githubusercontent.com/98904988/163063703-72f8f65e-bff4-4e89-bd90-a05bf601f8ea.png)

**Comment by BeatrizPer** [comment]
ask Andrew and Aron to review and see if parts are missing/different

**Comment by BeatrizPer** [comment]
Waiting on Andrew to provide resistor values and count @computer-lov

**Comment by BeatrizPer** [comment]
moving to done, will review at end
