### ISSUE TITLE
Demo video

### ISSUE THREAD

**Issue by arongoldberg** [computer-lov/Nighttime-Parenting-Device#26]

**Comment by BeatrizPer** [comment]
Aron and Andrew are filming it and sending it to me (Beatriz) to edit and submit it

**Comment by BeatrizPer** [comment]
I successfully edited the whole Demo Video, can be seen here https://drive.google.com/drive/folders/1vIirP8cHmlwjsHTsjVYJ51R7UmfQbCNn?usp=sharing
