### ISSUE TITLE
Fill in Stub Functions for LED Bar

### ISSUE THREAD

**Issue by arongoldberg** [computer-lov/Nighttime-Parenting-Device#36]
- [x] Commit reference
- [x] Describe how to use function
- [x] Describe design decisions
- [x] Describe test

**Comment by BeatrizPer** [comment]
Accomplished after doing project specific tests

**Comment by BeatrizPer** [comment]
Reviewed and done

**Comment by BeatrizPer** [comment]
check #50 for evidence
