### ISSUE TITLE
Project specific tests: Microphone

### ISSUE THREAD

**Issue by computer-lov** [computer-lov/Nighttime-Parenting-Device#38]
- [x] describes and justify tests
- [x] explain how to do them
- [x] explain what results were

**Comment by computer-lov** [comment]
@ffund would it be okay if I used the CMA-4544PF-W microphone instead of the CMEJ-9745-37-p microphone for my individual parts report? The specifications for each are almost identical, however while working with both I have found that the CMA-4544PF-W is easier to work with because the terminal leads are longer than the other microphone. I can mention in my report that I worked with two microphones but ultimately decided to use one over the other. Also, I can  also make it clear that the AD2 data, datasheet screenshots, and software tests are coming from the CMA-4544PF-W microphone.  I am just asking because the CMEJ-9745-37-p was the first choice for my design originally and the CMA-4544PF-W was not.

**Comment by ffund** [comment]
@computer-lov that's fine, no problem.

**Comment by computer-lov** [comment]
I am placing this issue under review. The bullet points in this issue above are covered in section 2 and 3 in my individual parts report. 

Link:
https://docs.google.com/document/d/1B9sd3u-u8swBZ98E6752jMQrhfnkgwvYMWnpLR8MzK4/edit?usp=sharing

**Comment by computer-lov** [comment]
Reviewed and done
