### ISSUE TITLE
Understand and explain stereo decoder in more depth

### ISSUE THREAD

**Issue by BeatrizPer** [computer-lov/Nighttime-Parenting-Device#41]
- [x]  add instructions for how to understand the part (with reference to datasheet)

**Comment by arongoldberg** [comment]
Here is my [report](https://docs.google.com/document/d/1kdbbE0s_SRWqnf7UaaeJOfdQfKYee0BurwalORdZoKE/edit#heading=h.2m3kmwvr9xuo)
