### ISSUE TITLE
Project Specific Tests: Heart Rate Sensor

### ISSUE THREAD

**Issue by computer-lov** [computer-lov/Nighttime-Parenting-Device#42]
- [x] describes and justify tests
- [x] explain how to do them
- [x] explain what results were

**Comment by BeatrizPer** [comment]
temperature test is written below
```
    def getTemp(self):
        # temperature read in integer and fraction, both added
        # to find total temp
        
        # Enabling the temperature reading
        i2c.write_byte_data(HR_ADDR, 0x21, 1) # TEMP_EN
        i2c.write_byte_data(HR_ADDR, 0x03, 1) #DIE_TEMP_RDY_EN
        
        # Address for temp int = 0x1F
        T_int = i2c.read_byte_data(HR_ADDR, 0x1F)
        # Address for temp frac = 0x20
        T_frac = i2c.read_byte_data(HR_ADDR, 0x20)
        
        temp = T_int + T_frac
        return temp
```

**Comment by BeatrizPer** [comment]
The testing code function (main.py) is responsible for calling the heart rate monitor and starting up the sensor to begin the readings. After cloning the repository, the following code is ran to execute the code on the board.

<img width="265" alt="Screen Shot 2022-03-01 at 1 38 48 PM" src="https://user-images.githubusercontent.com/98904988/156228857-d24566fc-9dcd-4aff-9510-ff3d65fa6954.png">

The MAX30102 should turn on, ready to get its first reading. This is indicated by the red LED light on the finger pad sensor seen above.
After the light has turned on, a finger can be placed right on the light as shown in the picture below. 
<img width="285" alt="Screen Shot 2022-03-01 at 1 39 12 PM" src="https://user-images.githubusercontent.com/98904988/156228912-19f1f62f-e7d4-40bb-acd4-f3a778104816.png">

After the finger has been on the sensor for a few seconds, the terminal begins to print out BPM and SPO2 readings. The following figure below shows a few readings returned after I placed my finger on the sensor as explained above.
Although these readings appear to be accurate, there were a few outliers that were returned that were ignored. With these readings, the MAX30102 Heart Rate Sensor has successfully been set up and works!

<img width="359" alt="Screen Shot 2022-03-01 at 1 39 38 PM" src="https://user-images.githubusercontent.com/98904988/156228972-814e51ee-9b90-4d80-880b-e3a3ed089bfe.png">
