### ISSUE TITLE
Check part "liveness" for Microphone

### ISSUE THREAD

**Issue by arongoldberg** [computer-lov/Nighttime-Parenting-Device#46]
- [x] photo/schematic
- [x] code and/or instructions
- [x] expected result of "liveness" test

**Comment by computer-lov** [comment]
I completed the liveness tests and report section for it.

**Comment by computer-lov** [comment]
![image](https://user-images.githubusercontent.com/62214215/155378295-f1ac6efb-bee6-4606-9663-3d2d16bbe919.png)

Image of multimeter reading to confirm "liveness"

![image](https://user-images.githubusercontent.com/62214215/155378521-b9ff8385-e8a7-4343-a450-3c3b101947e6.png)

Image of Oscilloscope Reading of Op-Amp output when "Careless Whisper" is playing in background

**Comment by computer-lov** [comment]
Reviewed and done
