### ISSUE TITLE
Compile user research for personas

### ISSUE THREAD

**Issue by computer-lov** [computer-lov/Nighttime-Parenting-Device#58]
- [x] google user stories
- [x] gather quotes

**Comment by computer-lov** [comment]
I went on Amazon, Target, and Walmart's websites and compiled quotes about a few different baby monitor devices. All of the quotes are in this document below.

https://docs.google.com/document/d/1TkN1xzfGtXkWzfaGBC5YBUw5xu6LE0pQQahO6MX0JX0/edit#

**Comment by computer-lov** [comment]
Reviewed and done

**Comment by BeatrizPer** [comment]
updated user research after getting feedback from professor, task switched from Andrew to Beatriz
<img width="940" alt="Screen Shot 2022-05-10 at 12 54 25 PM" src="https://user-images.githubusercontent.com/98904988/167682036-2a1c7c8a-5745-46ca-a75f-e2681acc233d.png">
