### ISSUE TITLE
Confirm current consumption of heart rate sensor

### ISSUE THREAD

**Issue by BeatrizPer** [computer-lov/Nighttime-Parenting-Device#6]
Testing will be done once part comes in to confirm current consumption of the heart rate sensor

**Comment by BeatrizPer** [comment]
1.4Amps? as team about this

**Comment by computer-lov** [comment]
![hrsensorcurrentconsumption](https://user-images.githubusercontent.com/62214215/161873499-ba9ef6ae-9d90-4dd2-842c-5f22cbdbae36.jpg)

Found total current consumption to be 28.32 mA.

**Comment by computer-lov** [comment]
Since I am testing hr sensor code. I figured I would also complete this task.

**Comment by computer-lov** [comment]
Attempted to read current with multimeter. Only receiving 0.0 reading. I believe the fuse in the multimeter is blown. Will try with new multimeter tomorrow.
