### ISSUE TITLE
Wireframe for browser-based UI

### ISSUE THREAD

**Issue by arongoldberg** [computer-lov/Nighttime-Parenting-Device#60]

**Comment by BeatrizPer** [comment]
still need to add in browser a section to send message to oled display

**Comment by BeatrizPer** [comment]
current browser design
![image](https://user-images.githubusercontent.com/98904988/160671447-4c1306ee-7983-4768-bb29-99e42d3c7a91.png)

**Comment by BeatrizPer** [comment]
Removing "My average heart beat is"

and including other pages on user interface

![image](https://user-images.githubusercontent.com/98904988/160891648-f78ae9db-d8dc-4a3d-baab-c2422d1a642a.png)

![image](https://user-images.githubusercontent.com/98904988/160891446-b7ca2a64-65ab-432c-a4eb-c381da5293d3.png)

![image](https://user-images.githubusercontent.com/98904988/160891489-44adacad-03fc-441e-9cb4-ec988ff9ea6d.png)

**Comment by BeatrizPer** [comment]
Moving to done
