### ISSUE TITLE
Create affinity map

### ISSUE THREAD

**Issue by computer-lov** [computer-lov/Nighttime-Parenting-Device#62]
- [ ] create affinity map like in class example

**Comment by computer-lov** [comment]
Created an affinity map from the compiled user research using Jamboard.

https://jamboard.google.com/d/1haQbWqZEbhgPHvbV2ly60fo2-vuMrqLiXxJ_AHvrjAY/viewer?f=0

**Comment by computer-lov** [comment]
Moving to done.

**Comment by computer-lov** [comment]
Reassigned to Beatriz

**Comment by BeatrizPer** [comment]
Working on getting user stories to be centered towards parenting and not on existing devices

**Comment by BeatrizPer** [comment]
Asked for feedback from Andrew and Aron on affinity map created 
![image](https://user-images.githubusercontent.com/98904988/161465982-085bdb3c-e3cb-43b3-9793-20e714af5251.png)

**Comment by BeatrizPer** [comment]
![image](https://user-images.githubusercontent.com/98904988/161466023-4d61445d-009e-4f4e-baf9-2f4df9234b2b.png)
Will update night time care causes guilt part

**Comment by BeatrizPer** [comment]
Added new stories and added the personas on scale
![image](https://user-images.githubusercontent.com/98904988/161469403-48f8c22e-52f2-4df5-b100-2b5c65ca05d8.png)

**Comment by BeatrizPer** [comment]
@ffund Can you review our affinity map/personas?
https://jamboard.google.com/d/1haQbWqZEbhgPHvbV2ly60fo2-vuMrqLiXxJ_AHvrjAY/edit?usp=sharing

**Comment by BeatrizPer** [comment]
Adjusting affinity map per Professor feedback

- Find more user stories where people are more chill about night time parenting for the left extreme
- Change guilt section to be more specific - guilty about what? (Now centering towards sleep training and emotions to that)

**Comment by BeatrizPer** [comment]
![image](https://user-images.githubusercontent.com/98904988/163634398-99890aba-a099-41a2-a5e1-43f515f09fed.png)
updated
