### ISSUE TITLE
Improve getPkPkAvg() function

### ISSUE THREAD

**Issue by computer-lov** [computer-lov/Nighttime-Parenting-Device#64]
- [x]  improve this function in nighttimeParenting.py 
- [ ]  test the new code

**Comment by computer-lov** [comment]
Created a new function to help getPKPkAvg() function.

![image](https://user-images.githubusercontent.com/62214215/157472385-d39d977d-ca80-45ca-807c-994c7139682a.png)

**Comment by BeatrizPer** [comment]
moving to done, works regularly per andrew
