### ISSUE TITLE
Confirm current consumption of stereo decoder

### ISSUE THREAD

**Issue by BeatrizPer** [computer-lov/Nighttime-Parenting-Device#7]
Testing will be done once part comes in to confirm current consumption of the stereo decoder

**Comment by arongoldberg** [comment]
Measured 8mA but with static coming through the headphones

**Comment by arongoldberg** [comment]
Measured about 6.8mA at 20% volume, around 7.2mA at 50% volume and up to 8.3mA at max volume, and around 3.1ma with no music playing. Not sure why I got static last time when measuring but this time it worked without any tricks and music came through. @ffund you told me that you think 8mA is too low, but that's what I keep getting, is that ok?

**Comment by ffund** [comment]
That's fine @arongoldberg
