### ISSUE TITLE
Confirm current consumption of OLED screen

### ISSUE THREAD

**Issue by BeatrizPer** [computer-lov/Nighttime-Parenting-Device#8]
Testing will be done once part comes in to confirm current consumption of the OLED screen

**Comment by arongoldberg** [comment]
I've confirmed that the OLED turns on via `i2cdetect -y 1` showing the expected address of 0x3d, and an indicator LED on the back lighting up:
![litup](https://user-images.githubusercontent.com/89358150/158276027-7ea65967-9b29-4af2-89cf-455e3d00d8b4.jpg)


I've run `pip3 install adafruit-circuitpython-ssd1327` to install the library for this display. I am trying to run [this](https://learn.adafruit.com/adafruit-grayscale-1-5-128x128-oled-display/circuitpython-wiring-and-usage#example-code-3076925-29) demo to see how much current is consumed when the screen is on.  When I try to run the code, I get a module not found error, and attempting to run `pip3 install adafruit-circuitpython-displayio` doesn't work either: 
<img width="958" alt="displayioError" src="https://user-images.githubusercontent.com/89358150/158276702-fea99c51-2678-40b3-a999-5ebb940f4fb9.png">

There are some instructions [here](https://learn.adafruit.com/adafruit-grayscale-1-5-128x128-oled-display/circuitpython-wiring-and-usage#circuitpython-displayio-library-installation-3076879-8) that I was going to try but I don't really know what to download or where to copy it. After googling around, I don't think displayio is available without installing CircuitPython. I'm not too sure about that however, and I don't know what to do next in any case. @ffund can you please help me out?

**Comment by arongoldberg** [comment]
@ffund Thank you, I installed those packages which allowed me to successfully run the example program. However, the screen remains off when I run the code. Here is a picture of what my AD2 picks up when I run the program: 
<img width="960" alt="i2cProtocol" src="https://user-images.githubusercontent.com/89358150/158702906-23ce477c-f58a-41c0-adfb-c42cb169b05a.png">
Reading the [datasheet](https://www.generationrobots.com/media/Ecran_OLED_0_96/SSD1327_datasheet.pdf) command table (sections 9 and 10), it looks like the first command, AE, turns the display off, the next bunch of commands configure various things, and the third to last one, AF, should turn the display on. Then a bunch of data is sent to GDDRAM to be displayed: 
<img width="960" alt="protocol2" src="https://user-images.githubusercontent.com/89358150/158731790-022e0a56-8a61-41fc-9ac3-c0b737389aa1.png">
I believe at this point the display should be on and there should be something on it, however it is still off.

**Comment by arongoldberg** [comment]
@ffund Thank you, I installed those packages which allowed me to successfully run the example program. However, the screen remains off when I run the code. Here is a picture of what my AD2 picks up when I run the program: 
<img width="960" alt="i2cProtocol" src="https://user-images.githubusercontent.com/89358150/158702906-23ce477c-f58a-41c0-adfb-c42cb169b05a.png">
Reading the [datasheet](https://www.generationrobots.com/media/Ecran_OLED_0_96/SSD1327_datasheet.pdf) command table (sections 9 and 10), it looks like the first command, AE, turns the display off, the next bunch of commands configure various things, and the third to last one, AF, should turn the display on. Then a bunch of data is sent to GDDRAM to be displayed: 
<img width="960" alt="protocol2" src="https://user-images.githubusercontent.com/89358150/158731790-022e0a56-8a61-41fc-9ac3-c0b737389aa1.png">
I believe at this point the display should be on and there should be something on it, however it is still off.

**Comment by ffund** [comment]
@arongoldberg Perhaps try the Luma library? https://github.com/rm-hull/luma.oled

**Comment by arongoldberg** [comment]
@ffund I've tried to run the basic Luma test as well as some examples and they all result in a blank screen. Should we switch to a different OLED display?

**Comment by ffund** [comment]
Sure @arongoldberg you can use the SSD1306-based display from DP1 if you prefer.

**Comment by ffund** [comment]
@arongoldberg I had another of those 128x128 grayscale OLEDs around, and I tested it. I was able to run

```
sudo pip3 install luma.oled
git clone https://github.com/rm-hull/luma.examples
cd luma.examples/
python3 clock.py --display ssd1327 --height 128 --width 128 --i2c-address 0x3D
```

and get this:

![image](https://user-images.githubusercontent.com/2316553/161573130-316de10e-cf61-42b0-8663-5c7abd01137e.png)

If you want to try with the 128x128 OLED I used (in case you got a lemon), you can. Or, you can go with the SSD1306, your call.

**Comment by arongoldberg** [comment]
3.6mA static text at default contrast, 3.9-4.8mA with running clock at max contrast. This is on the SSD1306 0.96" OLED from the fall semester, as even the confirmed working 1.5" SSD1327 OLED did not work with my Pi.

**Comment by arongoldberg** [comment]
Reviewed and moved to done
