### ISSUE TITLE
Confirm current consumption of op-amp circuit

### ISSUE THREAD

**Issue by BeatrizPer** [computer-lov/Nighttime-Parenting-Device#9]
Testing will be done once part comes in to confirm current consumption of the op-amp circuit

**Comment by computer-lov** [comment]
The current consumption when the microphone was powered off was measured to be 0.03 mA.

![micOFF](https://user-images.githubusercontent.com/62214215/157290671-81cf1035-3638-4698-b31b-d9bd3508dea8.jpg)

The expected result was 0.0 mA. Therefore, the measured current is in agreement with the theoretical current.

The theoretical result was determine from this datasheet.

https://www.cuidevices.com/product/resource/cma-4544pf-w.pdf

**Comment by computer-lov** [comment]
The current consumption when the microphone is powered on was measured to be 332 uA. 

![micON](https://user-images.githubusercontent.com/62214215/157291322-1757f708-4761-4de6-bb4d-cffa7b7f24fa.jpg)

The absolute maximum rating for the current consumption in this part is 500 uA. Therefore, the theoretical result is in agreement with the measured result. 

The theoretical result was determined from this datasheet.

https://www.cuidevices.com/product/resource/cma-4544pf-w.pdf

**Comment by computer-lov** [comment]
The current consumption when the op-amp is powered off was measured to be 0.0 mA.

![opAmpOFF](https://user-images.githubusercontent.com/62214215/157292071-dd5954aa-87c3-4ab4-89c3-7af232df3c3d.jpg)

The specified value was also 0.0 mA. Therefore, the theoretical result is in agreement with the measured result.

The theoretical result was determined from this datasheet.

https://www.ti.com/lit/ds/symlink/opa344.pdf?HQS=dis-mous-null-mousermode-dsf-pf-null-wwe&ts=1646758941572&ref_url=https%253A%252F%252Fwww.google.com%252F

**Comment by computer-lov** [comment]
The current consumption when the op-amp was powered on was measured to be 330 uA. The current was measured by removing the op-amp and then placing the positive end of the multimeter on the wire connecting to the power supply and the negative-end to the wire connecting to the positive terminal of the op-amp. 

![opAmpON](https://user-images.githubusercontent.com/62214215/157295241-ded8c880-c36e-4179-92ea-19359de52f1d.jpg)

**Comment by computer-lov** [comment]
@ffund we are considering moving to done. Does the current look reasonable?

**Comment by ffund** [comment]
@computer-lov yes, seems OK.
